version: "3.1"
services:
  # Nginx Service
  web: 
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs/cloudflare/
    ports:
      - 80:80
      - 443:443
    networks: 
      - chat-networks
